FROM jenkins/jenkins:lts

USER root

# Installer Python et venv
RUN apt-get update && \
    apt-get install -y python3-pip python3-venv && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN chown -R jenkins:jenkins /var/jenkins_home

USER jenkins

EXPOSE 8080 50000
